<?php /* @var $this \Magelight\Admin\Blocks\Body */ ?>
<div class="navbar-container">
    <div class="navbar navbar-static-top">
        <div class="navbar-inner">
            <?=$this->section('admin_navbar')?>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span2">
        <?=$this->section('admin_sections')?>
    </div>
    <div class="span10">
        <?=$this->section('content')?>
    </div>
</div>