<?php
/* @var $this \Cargo\Blocks\Order\OrderList */
?>

<h1>Заявки</h1>

<?=$this->section('orders-pager'); ?>
<div class="row">
<table class="table table-hover table-striped span12">
    <thead>
        <tr>
            <th class="span5">Описание</th>
            <th class="span4">Маршрут</th>
            <th class="span2">Дата</th>
            <th class="span2">Макс. цена</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->get('orders', []) as $order): ?>
            <tr>
                <td>
                    <p><?=$order['details']?></p>
                    <p>
                        <?php if ($order['weight']): ?>
                            <span class="badge badge-important">Вес: <?=$order['weight']?> кг</span>
                        <?php endif; ?>
                        <?php if ($order['passengers']): ?>
                            <span class="badge badge-info">Пассажиров: <?=$order['passengers']?></span>
                        <?php endif; ?>
                    </p>
                </td>
                <td>
                    <p class="">Откуда: <?=$order['city_from'] . ', '  . $order['address_from']?></p>
                    <p class="">Куда: <?=$order['city_to'] . ', '  . $order['address_to']?></p>

                    <span class=""><?=@round($order['route_length'] / 1000, 1)?> км</span>,
                    ~ <strong class=""><?=$this->formatTime($order['route_time'])?></strong>
                </td>
                <td><?=($order['date_move'] ? $this->date($order['date_move']) : '-')?></td>
                <td><strong><?=$order['max_price']?> грн.</strong></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
</div>
<?=$this->section('orders-pager'); ?>
