<?php
/* @var $this \Cargo\Blocks\Order\OrderForm */
?>

<div class="page-header">Заказать перевозку</div>

<div class="row">
    <div class="span8">
        <form name="<?=$this->getAttribute('name')?>" class="<?=$this->getAttribute('class')?>" action="<?=$this->getAttribute('action')?>" method="<?=$this->getAttribute('method')?>">
            <div class="control-group" >
                <ul id="category-selector" class="categories">
                    <?php foreach ($this->get('categories', []) as $category): ?>
                    <li>
                        <a id="category-select-link-<?=$category['id']?>" class="category-link" href="#" data-category="<?=$category['id']?>">
                            <div class="category-icon cat-icon-<?=$category['id']?>"></div><span class="category-title"><?=$category['title']?></span>
                        </a>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <div class="control-group hidden"  id="current-category">
                <label class="control-label">Категория</label>
                <div class="controls">
                    <ul class="selected-category">
                        <li>
                            <span>
                                <div class="category-icon"></div>
                                <span class="category-title"></span>
                            </span>
                            <a id="category-change-link" href="#">
                                <span class="">(Изменить)</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <input id="order-category" type="hidden" name="<?=$this->wrapName('category')?>" value="<?=$this->getFieldValue('category')?>"/>
                <script type="text/javascript">
                    function selectCategory(category_id)
                    {
                        var linkElement = $('#category-select-link-' + category_id);
                        if (linkElement) {
                            $('#order-category').val(category_id);
                            $('#category-selector').hide(100);
                            $('#current-category').show(100)
                                    .find('ul li div.category-icon').attr('class', 'category-icon cat-icon-' + category_id)
                                    .parent().find('span.category-title').text($(linkElement).find('span.category-title').text());
                        }
                    }
                    $(document).ready(function(){
                        var order_category = $('#order-category').val();
                        if (order_category) {
                            selectCategory(order_category);
                        }
                        $('ul.categories li a.category-link').bind('click', function(){
                            selectCategory($(this).attr('data-category'));
                        });
                        $('#category-change-link').bind('click', function(){
                            $('#category-selector').show(100);
                            $('#current-category').hide(100);
                            $('#order-category').val('');
                        });
                    });
                </script>
            </div>
            <div class="control-group">
                <label class="control-label" for="order-location-from-city">Откуда <span class="required">*</span></label>
                <div class="controls">
                    <input id="order-location-from-city" class="span4" data-provide="typeahead" data-source='<?=$this->get('cities', '[]')?>' data-items="5" name="order[city_from]" value="<?=$this->getFieldValue('city_from')?>" type="text" placeholder="Город" />
                    <input id="order-location-from-address" class="span6" name="order[address_from]" value="<?=$this->getFieldValue('address_from')?>" type="text" placeholder="Адрес"/>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="order-location-to-city">Куда <span class="required">*</span></label>
                <div class="controls">
                    <input id="order-location-to-city" class="span4" data-provide="typeahead" data-source='<?=$this->get('cities', '[]')?>' data-items="5" name="order[city_to]" value="<?=$this->getFieldValue('city_to')?>" type="text" placeholder="Город"/>
                    <input id="order-location-to-address" class="span6" name="order[address_to]" type="text" value="<?=$this->getFieldValue('address_to')?>" placeholder="Адрес"/>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="order-details">Что везем</label>
                <div class="controls">
                    <textarea id="order-details" class="span10" name="order[details]" placeholder="Подробнее о заказе (что везем). Габариты, объем, пожелания и требования."><?=$this->getFieldValue('details')?></textarea>
                </div>

            </div>
            <div class="control-group">
                <div class="controls">
                    <a data-toggle="collapse" href="#order-details-block"><strong>Указать детали</strong></a>
                </div>
            </div>
            <div id="order-details-block" class="collapse in" style="height: 0">

                <div class="control-group">
                    <label class="control-label" for="order-weight">Вес груза</label>
                    <div class="controls">
                        <div class="input-append">
                            <input id="order-weight" class="span10" name="order[weight]" value="<?=$this->getFieldValue('weight')?>" type="text"/>
                            <span class="add-on">кг</span>
                        </div>
                        <span class="help-inline">примерно</span>
                    </div>
                </div>

                <div class="control-group">
                    <div class="controls">
                        <label class="checkbox inline">
                            <input type="checkbox" name="order[loading_required]" value="1" <?php if ($this->getFieldValue('loading_required')): ?>checked="checked"<?php endif; ?>/>
                            Нужна погрузка/разгрузка
                        </label>
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="order-passengers">Пассажиры</label>
                    <div class="controls">
                        <div class="input-append">
                            <input id="order-passengers" class="span7" name="order[weight]" value="<?=$this->getFieldValue('passengers')?>" type="text"/>
                            <span class="add-on">человек</span>
                        </div>

                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="order-date">Дата</label>
                    <div class="controls">
                        <input id="order-date" class="span4 datepicker" size="16" name="order[date_move]" value="<?=$this->getFieldValue('date_move')?>" placeholder="<?=$this->get('current_date', '')?>" type="text"/>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="order-max-price">Максимальная цена</label>
                    <div class="controls">
                        <div class="input-append">
                            <input id="order-max-price" class="span10" name="order[max_price]" value="<?=$this->getFieldValue('max_price')?>" type="text"/>
                            <span class="add-on">грн.</span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="order-max-price">Ваши контакты <span class="required">*</span></label>
                <?php $client = $this->getFieldValue('client'); ?>
                <div class="controls">
                    <input id="order-client-name" class="span10" name="order[client][client_name]" value="<?=$client['client_name']?>" type="text" placeholder="Имя"/>
                </div>
                <div class="controls">
                    <input id="order-client-email" class="span10" name="order[client][client_email]" value="<?=$client['client_email']?>" type="text" placeholder="E-Mail"/>
                </div>
                <div class="controls">
                    <input id="order-client-phone" class="span10 masked-input" data-mask="+38 (999) 999-99-99" name="order[client][client_phone]" value="<?=$client['client_phone']?>" type="text" placeholder="Телефон"/>
                </div>
            </div>

            <?=$this->getResultRowHtml();?>

            <div class="control-group">
                <div class="controls">
                    <button class="btn btn-primary">Разместить заявку</button>
                </div>
            </div>
        </form>
    </div>
    <div class="span4 container-fluid">
        <div class="alert alert-info">
            <p><i class="icon-exclamation-sign"></i> Важно!</p>
            <p>Размещая заявку Вы соглашаетесь с правилами сервиса</p>
            <p>Администрация сервиса не несет ответственности за действия перевозчиков и курьеров</p>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $('.datepicker').datepicker({
            dates: {
                days: ["Воскресенье", "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота", "Воскресенье"],
                daysShort: ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"],
                daysMin: ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"],
                months: ["Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"],
                monthsShort: ["Янв", "Фев", "Мар", "Апр", "Май", "Июн", "Июл", "Авг", "Сен", "Окт", "Ноя", "Дек"]
            },
            weekStart: 1,
            format: 'dd.mm.yyyy'
        });
        $('.typeahead').typeahead();
        $('#order-details-toggle').bind('click', function(){
            $('#order-details-block').toggleClass('hidden');
        });
        $(".collapse").collapse();
    });
</script>


