<?php
    /* @var \Magelight\Webform\Blocks\Elements\FilePretty $this */
?>

<input id="<?php echo $this->getId() ?>-hidden" type="file" style="display:none" name="<?php echo $this->getName() ?>" />
<div class="input-group">
    <input id="<?php echo $this->getId() ?>" class="<?php echo $this->getAttribute('class') ?>" type="text" />
    <a class="btn" onclick="$('input[id=<?php echo $this->getId() ?>-hidden]').click();"><?php echo $this->title ?></a>
</div>

<script type="text/javascript">
    $('input[id=<?php echo $this->getId() ?>-hidden]').change(function() {
        $('#<?php echo $this->getId() ?>').val($(this).val());
    });
</script>