<?php
/**
 * @var \Magelight\Core\Blocks\Grid $this
 */
?>
<form <?=$this->getFilterForm()->renderAttributes()?>>
    <div class="filter-row">
        <button class="btn btn-xs btn-info"><?=__('Apply filters')?></button>
        <button class="btn btn-xs"><?=__('Reset filters')?></button>
    </div>
    <table class="<?=$this->class?> grid table">
        <thead>
            <tr>
                <?php foreach ($this->getColumns() as $key => $column) { ?>
                    <th>
                        <?php if ($column->isSortable()) { ?>
                            <a href="#" data-sort="<?=$column->getSortField()?>" data-sort-dir="<?=$this->getFilterForm()->getFieldValue("sort[{$column->getSortField()}]")?>"><?=$this->escapeHtml($column->getTitle())?></a>
                        <?php } else { ?>
                            <span><?=$this->escapeHtml($column->getTitle())?></span>
                        <?php } ?>
                    </th>
                <?php } ?>
            </tr>
        </thead>
        <tbody>
            <tr class="filter-row">
                <?php foreach ($this->getColumns() as $key => $column) { ?>
                    <td>
                        <?php if ($column->getFilter()) { ?>
                            <div>
                                <?=$column->getFilter()->toHtml()?>
                            </div>
                        <?php } ?>
                    </td>
                <?php } ?>
            </tr>
        </tbody>
        <tbody>
            <?php foreach ($this->getRows() as $row) { ?>
            <tr>
                <?php foreach ($this->getColumns() as $column) { ?>
                    <td><?=$this->renderCellContent($column, $row)?></td>
                <?php } ?>
            </tr>
            <?php } ?>
        </tbody>
    </table>
</form>
<div class="text-center">
    <?=$this->pager->toHtml()?>
</div>
