<?php
/* @var $this \Magelight\Core\Blocks\Pager */
?>

<ul <?=$this->renderAttributes()?>>
    <?php foreach ($this->get('pages', []) as $page) : ?>
        <li class="<?php if ($page['disabled']): ?>disabled<?php endif; ?> <?php if ($page['active']): ?>active<?php endif; ?>">
            <a href="<?=(!$page['disabled']) ? $page['url'] : '#';?>">
                <?=$page['caption']?>
            </a>
        </li>
    <?php endforeach; ?>
</ul>