<?php
/* @var $this \Magelight\Scaffold\Blocks\Entities */
?>

<table class="table">
    <thead>
        <tr>
            <th>Entity</th>
            <th>Comment</th>
            <th>Count</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->entities as $entity) : ?>
            <tr>
                <td><a href="<?=$this->url('scaffold/{entity}/page-0', ['entity' => $entity['entity']])?>"><?=$entity['entity']?></a></td>
                <td><?=$entity['comment']?></td>
                <td><?=$entity['count']?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>