<div class="page-header">Welcome</div>

<p>Congratulations! You have successfully installed <strong>Magelight</strong>, the lightweight framework inspired by Magento.</p>

<p>This is <strong><?php echo __FILE__?></strong> template, rendered by <strong>Maelight/Core/Blocks/Index</strong> block.
    You can modify this template or block or otherwise redefine the Index block in your own module or redefine it in public code pool.
    <em>(A link for tutorial should be present here.)</em>
</p>
<p>Markup and styling assist: <a href="http://twitter.github.com/bootstrap/" target="_blank">Twitter Bootstrap</a>.</p>