<div class="page-header">
    <h1>Welcome</h1>
</div>

<p>Congratulations! You have successfully installed <strong>Magelight</strong>, the lightweight framework inspired by Magento.</p>

<p>This is <strong><?php echo __FILE__?></strong> template, rendered by <strong>Maelight/Core/Blocks/Index</strong> block.</p>

<p>You can modify this template or block or otherwise redefine the Index block in your own module or redefine it in public code pool.</p>

<p><em>(A link for tutorial should be present here.)</em></p>

<p>Markup and styling assist: <a href="http://twitter.github.com/bootstrap/" target="_blank">Twitter Bootstrap</a>.</p>