<?
    /* @var $this \Magelight\Core\Blocks\Top */
?>
<div class="navbar ">
    <div class="navbar-inner">

        <ul class="nav">
            <li><a href="<?php echo $this->url('/'); ?>">Home</a></li>
            <li><a href="<?php echo $this->url('unexistent'); ?>">Unexistent page</a></li>
        </ul>

        <ul class="nav pull-right">
            <li><a href="#login-modal" role="button" class="" data-toggle="modal" >Login</a></li>
            <li><a href="<?php echo $this->url('register'); ?>">Register</a></li>
        </ul>

    </div>
</div>

<div id="login-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="login-modal-label" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i></button>
        <h3>Log into app</h3>
    </div>
    <div class="modal-body">
        <?php echo $this->getLoginFormHtml() ?>
    </div>
</div>