<?
    /* @var $this \Magelight\Core\Blocks\Top */
?>
<div class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
        <div class="container">
            <ul class="nav">
                <li><a href="<?php echo $this->url('/'); ?>"><i class="icon-home icon-white"></i> Home</a></li>
                <li><a href="<?php echo $this->url('unexistent'); ?>">Unexistent page</a></li>

            </ul>

            <ul class="nav pull-right">
                <li><a href="#login-modal" role="button" class="" data-toggle="modal" >Login</a></li>
                <li><a href="<?php echo $this->url('register'); ?>">Register</a></li>
                <li>

                    <form name="search" id="search-form" class="navbar-form">
                        <div class="input-append">
                            <input type="text" id="search-field" name="query" placeholder="Search...">
                            <span class="add-on">
                                <i class="icon-search"></i>
                            </span>
                        </div>
                    </form>
                </li>

            </ul>
        </div>
    </div>
</div>

<div id="login-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="login-modal-label" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i></button>
        <h3>Log into app</h3>
    </div>
    <div class="modal-body">
        <?php echo $this->getLoginFormHtml() ?>
    </div>
</div>