<?php /* @var $this \SampleApp\Blocks\UserProfile */ ?>
<h1><?=$this->user['name']?></h1>
<img class="thumbnail" alt="<?=$this->user['name']?>" src="<?=$this->user['photo']?>" />

<dl>
    <dt>Name</dt>
    <dd><?=$this->user['name']?></dd>

    <dt>E-mail</dt>
    <dd><?=$this->user['email']?></dd>

    <dt>Location</dt>
    <dd><?=$this->user['country']?>, <?=$this->user['city']?></dd>

    <dt>Url</dt>
    <dd><?=$this->user['openid_identity']?></dd>
</dl>