<?php

namespace Magelight\Config\Blocks\Config\Form;

use Magelight\Core\Blocks\Element;

class Row extends \Magelight\Webform\Blocks\Row
{

    public function addField($field, $label = null, $hint = null)
    {
        return parent::addField($field, $label, $hint); // TODO: Change the autogenerated stub
    }
}
