<h3>Welcome</h3>

<p>Congratulations! You have successfully installed <strong>Magelight</strong>, the lightweight framework inspired by Magento.</p>
<p>This is Core/templates/index.phtml template, rendered by Core/Blocks/Index block.
You can modify this template or block or otherwise redefine the Index block in your own module.</p>
<p>All styles and markup are made with <a href="http://twitter.github.com/bootstrap/" target="_blank">Twitter Bootstrap</a> framework, included in Core module.</p>