<div class="navbar ">
    <div class="navbar-inner">
        <div class="container">
        <ul class="nav">
            <li><a href="<?php echo $this->url('/'); ?>">Home</a></li>
            <li><a href="<?php echo $this->url('login'); ?>">Login</a></li>
            <li><a href="<?php echo $this->url('register'); ?>">Register</a></li>
            <li><a href="<?php echo $this->url('feedback'); ?>">Feedback</a></li>
            <li><a href="<?php echo $this->url('unexistent'); ?>">Unexistent page</a></li>
        </ul>
        <form class="navbar-form pull-right">
            <input type="text" class="" placeholder="Search..." />
        </form>
        </div>
    </div>
</div>