<div class="navbar ">
    <div class="navbar-inner">

        <ul class="nav">
            <li><a href="<?php echo $this->url('/'); ?>">Home</a></li>
            <li><a href="<?php echo $this->url('unexistent'); ?>">Unexistent page</a></li>
        </ul>

        <ul class="nav pull-right">
            <li><a href="<?php echo $this->url('login'); ?>">Login</a></li>
            <li><a href="<?php echo $this->url('register'); ?>">Register</a></li>
        </ul>

    </div>
</div>