<?php
/* @var $this \Magelight\Block */
?>

<ul class="nav pull-right">
    <?php if (!$this->getGlobal('user_data', false)): ?>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Войти<b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li>
                <dl class="login-options">
                    <dt>Через сервисы</dt>
                    <dd>
                        <?php echo $this->section('ulogin-widget') ?>
                    </dd>
                    <dt>
                        Стандартный вход
                    </dt>
                    <dd>
                        <form class="form-inline form-search navbar-form" action="<?php echo $this->url('login')?>" method="post">
                            <div class="controls-row">
                                <input type="text" class="input-small" name="login-form[email]" placeholder="Ваш e-mail" />
                                <input type="password" class="input-small" name="login-form[password]" placeholder="Пароль" />
                                <button class="btn">Войти</button>
                            </div>
                        </form>
                        <div class="reg-options">
                            <a href="<?=$this->url('remindpass'); ?>">Забыли пароль?</a>
                        </div>
                    </dd>
                </dl>
            </li>
        </ul>
    </li>
    <li>
        <a href="<?=$this->url('/register')?>">Регистрация</a>
    </li>
    <?php else: ?>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <img class="navbar-avatar" src="<?=$this->getGlobal('user_data')['photo']?>" alt="<?=$this->getGlobal('user_data')['name']?>" />
            <?=$this->getGlobal('user_data')['name']?>
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a><i class="icon-certificate"></i> Мои объявления</a></li>
            <li><a><i class="icon-envelope"></i> Мои сообщения</a></li>
            <li><a><i class="icon-wrench"></i> Настройки</a></li>
            <li><a><i class="icon-hand-right"></i> Счет</a></li>
            <li><a href="<?=$this->url('logout')?>"><i class="icon-remove"></i> Выход</a></li>
        </ul>
    </li>
    <?php endif; ?>

</ul>