<?php
    /* @var $this \Magelight\Auth\Blocks\User\Register */
?>
<h1>Регистрация</h1>
<div class="row-fluid">

    <div class="span7">
        <div class="page-header">
            Через форму
        </div>
        <div>
            <?=$this->section('register-user-form')?>
        </div>
    </div>

    <div class="span4">
        <div class="page-header">
            Через социальные сети
        </div>
        <div>
            <?=$this->section('ulogin-widget-register')?>
            <p></p>
            <div class="alert alert-info">
                При входе через социальную сеть регистрация производится автоматически
            </div>
        </div>
    </div>
</div>
