<?php
/* @var $this \Magelight\Auth\Blocks\User\Login */
?>
<h1>Sign in</h1>
<div class="row-fluid">

    <div class="span8">
        <div class="page-header">
            Via e-mail
        </div>
        <div>
            <?=$this->section('login-user-main-form')?>
        </div>
    </div>

    <div class="span4">
        <div class="page-header">
            Via services
        </div>
        <div>
            <?=$this->section('ulogin-widget-register')?>
        </div>
    </div>
</div>