<?php
/* @var $this \Magelight\Auth\Blocks\User\Login */
?>
<h1><?=__('Sign in')?></h1>
<div class="row">

    <div class="col-md-8">
        <div class="page-header">
            <?=__('Via e-mail')?>
        </div>
        <div>
            <?=$this->section('login-user-main-form')?>
        </div>
    </div>

    <div class="col-md-4">
        <div class="page-header">
            <?=__('Via services')?>
        </div>
        <div>
            <?=$this->section('ulogin-widget-register')?>
        </div>
    </div>
</div>