<?php
    /* @var $this \Magelight\Auth\Blocks\User\Register */
?>
<h1>Register</h1>
<div class="row-fluid">

    <div class="span8">
        <div class="page-header">
            Via e-mail
        </div>
        <div>
            <?=$this->section('register-user-form')?>
        </div>
    </div>

    <div class="span4">
        <div class="page-header">
            Via services
        </div>
        <div>
            <?=$this->section('ulogin-widget-register')?>
            <p></p>
            <div class="alert alert-info">
                Once you enter via service you`ll be registered automatically
            </div>
        </div>
    </div>
</div>
