<?php
/* @var $this \Magelight\Block */
?>

<ul class="nav pull-right">
    <?php if (!$this->getGlobal('user_data', false)): ?>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=__('Sign in')?><b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li>
                <dl class="login-options">
                    <dt><?=__('Via services')?></dt>
                    <dd>
                        <?php echo $this->section('ulogin-widget') ?>
                    </dd>
                    <dt>
                        <?=__('Standard log in')?>
                    </dt>
                    <dd>
                        <form class="form-inline form-search navbar-form" action="<?php echo $this->url('login')?>" method="post">
                            <div class="controls-row">
                                <input type="text" class="input-small" name="login-form[email]" placeholder="<?=__('E-mail')?>" />
                                <input type="password" class="input-small" name="login-form[password]" placeholder="<?=__('Password')?>" />
                                <button class="btn"><?=__('Sign in')?></button>
                            </div>
                        </form>
                        <div class="reg-options">
                            <a href="<?=$this->url('auth/remindpass'); ?>"><?=__('Remind password')?></a>
                        </div>
                    </dd>
                </dl>
            </li>
        </ul>
    </li>
    <li>
        <a href="<?=$this->url('/register')?>"><?=__('Register')?></a>
    </li>
    <?php else: ?>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <img class="navbar-avatar" src="<?=$this->getGlobal('user_data')['photo']?>" alt="<?=$this->getGlobal('user_data')['name']?>" />
            <?=$this->getGlobal('user_data')['name']?>
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a><i class="glyphicon glyphicon-certificate"></i> <?=__('My profile')?></a></li>
            <li><a href="<?=$this->url('logout')?>"><i class="glyphicon glyphicon-remove"></i> <?=__('Exit')?></a></li>
        </ul>
    </li>
    <?php endif; ?>
</ul>