<?php
    /* @var $this \Magelight\Auth\Blocks\User\Register */
?>
<h1><?=__('Register')?></h1>
<div class="row">

    <div class="col-md-8">
        <div class="page-header">
            <?=__('Via e-mail')?>
        </div>
        <div>
            <?=$this->section('register-user-form')?>
        </div>
    </div>

    <div class="col-md-4">
        <div class="page-header">
            <?=__('Via services')?>
        </div>
        <div>
            <?=$this->section('ulogin-widget-register')?>
            <p></p>
            <div class="alert alert-info">
                <?=__('Once you enter via service you`ll be registered automatically')?>
            </div>
        </div>
    </div>
</div>
