<?php
    /* @var $this \Magelight\Auth\Blocks\User\Register */
?>
<div class="page-header">
    <h1><?=__('Register')?></h1>
</div>
<div class="row">

    <div class="col-md-8">
        <div>
            <?=$this->section('register-user-form')?>
        </div>
    </div>

    <div class="col-md-4">
        <h2>
            <?=__('Enter via services')?>
        </h2>
        <div>
            <?=$this->section('ulogin-widget-register')?>
            <p></p>
            <div class="alert alert-warning">
                <?=__('Once you enter via service you`ll be registered automatically')?>
            </div>
        </div>
    </div>
</div>
