<?php
/**
 * @var \Magelight\Grid\Blocks\Grid $this
 */
?>
<form <?=$this->getFilterForm()->renderAttributes()?>>
    <div class="filter-row">
        <button class="btn btn-xs btn-info" type="submit"><?=__('Apply filters', [], 1, 'filters')?></button>
        <button class="btn btn-xs" type="reset"><?=__('Reset filters', [], 1, 'filters')?></button>
    </div>
    <table class="<?=$this->class?> grid table">
        <thead>
            <tr>
                <?php foreach ($this->getColumns() as $key => $column) { ?>
                    <th>
                        <?php if ($column->isSortable()) { ?>
                            <?php
                                $currentSortDir = $this->getFilterForm()->getFieldValue('sort[' . $column->getSortField() . ']');
                                // if sorted by ASC then new link is DESC
                                // if sorted by DESC then new link is null
                                // if no sorting then new link is ASC
                                $newSortDir = $currentSortDir == 'ASC'
                                    ? 'DESC' : ($currentSortDir == 'DESC' ? null : 'ASC');

                                $requestAppendParam = [
                                    $column->getSortField() => $newSortDir
                                ];
                                $filteringParams = [
                                    $this->getFilterForm()->getWrapIndex() => array_replace_recursive(
                                        $this->getFilterForm()->getRequestFields(),
                                        ['sort' => $requestAppendParam]
                                    )
                                ];
                            ?>
                            <a href="<?=$this->url($this->getUrlMatch(), $filteringParams)?>">
                                <?=$this->escapeHtml($column->getTitle())?>
                                <?php if ($currentSortDir) { ?>
                                    <i class="glyphicon glyphicon-sort-by-alphabet<?=$currentSortDir == 'DESC' ? '-alt' : ''?>"></i>
                                <?php } ?>
                            </a>
                        <?php } else { ?>
                            <span><?=$this->escapeHtml($column->getTitle())?></span>
                        <?php } ?>
                    </th>
                <?php } ?>
            </tr>
        </thead>
        <tbody>
            <tr class="filter-row">
                <?php foreach ($this->getColumns() as $key => $column) { ?>
                    <td>
                        <?php if ($column->getFilter()) { ?>
                            <div>
                                <?=$column->getFilter()->toHtml()?>
                            </div>
                        <?php } ?>
                    </td>
                <?php } ?>
            </tr>
        </tbody>
        <tbody>
            <?php foreach ($this->getRows() as $row) { ?>
            <tr>
                <?php foreach ($this->getColumns() as $column) { ?>
                    <td><?=$this->renderCellContent($column, $row)?></td>
                <?php } ?>
            </tr>
            <?php } ?>
        </tbody>
    </table>
</form>
<div class="text-center">
    <?php
        $this->setPagerRoute(
            $this->getUrlMatch(),
            [
                $this->getFilterForm()->getWrapIndex() => $this->getFilterForm()->getRequestFields()
            ]
        );
    ?>
    <?=$this->pager->toHtml()?>
</div>
