<?php /* @var $this \Magelight\Admin\Blocks\Navbar\Item */ ?>
<?php if (!$this->has_subitems) : ?>
    <li class="<?=$this->class?>">
        <a class="<?=$this->link_class?>" href="<?=$this->url($this->route)?>"><?=$this->title?></a>
    </li>
<?php else : ?>
    <li class="<?php if($this->is_bar_item): ?>dropdown<?php else: ?>dropdown-submenu<?php endif; ?> <?=$this->class?>">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->title?> <?php if($this->is_bar_item): ?><b class="caret"></b><?php endif; ?></a>
        <ul class="dropdown-menu">
            <?php foreach ($this->subitems as $item): ?>
                <?php
                /** @var $item \Magelight\Admin\Blocks\Navbar\Item */
                echo $item->toHtml();
                ?>
            <?php endforeach; ?>
        </ul>
    </li>
<?php endif; ?>
