<?php /* @var $this \Magelight\Visitors\Blocks\VisitorsSummary */ ?>
<div class="well">
    <table>
        <thead>
        <tr>
            <th>Today visitors</th>
            <th>Total visitors</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td><?=$this->today_count?></td>
            <td><?=$this->total_count?></td>
        </tr>
        </tbody>
    </table>
</div>
