<?php /* @var $this \Magelight\Visitors\Blocks\VisitorsSummary */ ?>

<?=$this->section('visitors-pager')?>

<table class="table">
    <thead>
        <tr>
            <th><?=__('Time');?></th>
            <th><?=__('IP');?></th>
            <th><?=__('Referer');?></th>
            <th><?=__('Summary');?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->get('visitors', []) as $visitor) : ?>
        <tr>
            <td><?=$this->dateTime($visitor['time'])?></td>
            <td><?=long2ip($visitor['ip'])?></td>
            <td><?=$this->escapeHtml(urldecode($visitor['referer']))?></td>
            <td>
                <a href="javascript:" onclick="$(this).parent().find('ul').toggle(100);">Show</a>
                <ul class="visitor-actions" style="display:none;">
                    <?php foreach (json_decode(gzuncompress($visitor['info']), true) as $requestRoute => $hitCount) : ?>
                        <li><?=$this->truncate($this->escapeHtml($requestRoute), 120)?> - <?=$hitCount?></li>
                    <?php endforeach; ?>
                </ul>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?=$this->section('visitors-pager')?>