<?php
    /* @var $this \Board\Blocks\Body*/
?>

<div class="container">
    <div class="row-fluid ">
        <div class="span14">
            <?php echo $this->section('top'); ?>
        </div>
    </div>
    <div class="row-fluid">
        <!--        <div class="span1">-->
        <!---->
        <!--        </div>-->
        <div class="span14 main-content">
            <?php echo $this->section('content'); ?>
        </div>
        <!--        <div class="span1">-->
        <!---->
        <!--        </div>-->
    </div>
</div>