<?php
/* @var $this \Board\Blocks\Top*/
?>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <ul class="nav">
                <li><a href="<?php echo $this->url('/'); ?>"><i class="icon-home"></i> Главная</a></li>
                <li><a href=""><i class="icon-plus"></i> Добавить объявление</a></li>
            </ul>
            <?=$this->section('login-menu-option')?>
        </div>
    </div>
</div>
