<?php /* @var $this \Magelight\Admin\Blocks\Body */ ?>
<div class="navbar-container">
    <div class="navbar navbar-default">
        <div class="navbar-inner">
            <?=$this->section('admin_navbar')?>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="container-fluid">
            <?=$this->section('breadcrumbs')?>
            <?=$this->section('content')?>
        </div>
    </div>
</div>