<?php
/* @var $this \Cargo\Blocks\Body*/
?>

<div class="container">
    <div class="row-fluid ">
        <div class="span12">
            <?php echo $this->section('top'); ?>
        </div>
    </div>
    <div class="row-fluid">
        <div class="row main-content">
            <?php echo $this->section('content'); ?>
        </div>
    </div>
</div>

<a id="move_up" href="#">&#x2191; Наверх</a>
<script type="text/javascript">
    $(function () {
        $(window).scroll(function () {
            if ($(this).scrollTop() > 100) $('a#move_up').fadeIn();
            else                           $('a#move_up').fadeOut(400);
        });
        $('a#move_up').click(function () {
            $('body,html').animate({
                scrollTop: 0
            }, 200);
            return false;
        });
    });
</script>